plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'ph.hublikha.rcn.transport'
version = '0.1.0'

android {
  namespace 'ph.hublikha.rcn.transport'
  defaultConfig {
    // Required by expo-module-gradle-plugin's publishing configuration.
    versionCode 1
    versionName '0.1.0'
  }
}

dependencies {
  implementation 'com.google.android.gms:play-services-nearby:19.3.0'
}
