package ph.hublikha.rcn.identity

import android.os.Build
import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyInfo
import android.security.keystore.KeyProperties
import android.util.Base64
import expo.modules.kotlin.exception.CodedException
import expo.modules.kotlin.modules.Module
import expo.modules.kotlin.modules.ModuleDefinition
import java.security.KeyFactory
import java.security.KeyPairGenerator
import java.security.KeyStore
import java.security.PrivateKey
import java.security.Signature
import java.security.spec.ECGenParameterSpec
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec

/**
 * Hardware-anchored identity, per ADR 0004 §1 and §2.
 *
 * Two keys live in the Android Keystore and neither is ever exported:
 *
 *  - an EC P-256 signing key, the device's long-term identity;
 *  - an AES-256 key used only to seal the X25519 agreement private key at rest.
 *
 * The X25519 key itself cannot live here — Keystore ECDH needs API 31+ and the
 * floor is 24 — so it is generated in TypeScript and handed back for sealing.
 * That key is in app memory while in use, which ADR 0004 records as a disclosed
 * weakening. The identity key never is.
 *
 * Nothing in this file parses an envelope or knows what a message is. It moves
 * bytes and signs them.
 */
class RcnIdentityModule : Module() {

  companion object {
    private const val KEYSTORE = "AndroidKeyStore"
    private const val IDENTITY_ALIAS = "rcn.identity.v1"
    private const val SEAL_ALIAS = "rcn.seal.v1"
    private const val SIGNATURE_ALGORITHM = "SHA256withECDSA"
    private const val GCM_TAG_BITS = 128
    private const val GCM_NONCE_BYTES = 12
  }

  private val keyStore: KeyStore by lazy {
    KeyStore.getInstance(KEYSTORE).apply { load(null) }
  }

  override fun definition() = ModuleDefinition {
    Name("RcnIdentity")

    /**
     * Returns the identity, creating it on first call. Idempotent: a second
     * call returns the same key, because a device that silently regenerated its
     * identity would lose every trust relationship its family had verified.
     */
    AsyncFunction("ensureIdentity") {
      if (!keyStore.containsAlias(IDENTITY_ALIAS)) {
        generateIdentityKey()
      }
      identityInfo()
    }

    AsyncFunction("getIdentity") {
      if (keyStore.containsAlias(IDENTITY_ALIAS)) identityInfo() else null
    }

    /**
     * Signs with the key inside the secure element. The private key is never
     * materialised here — the Keystore performs the operation.
     */
    AsyncFunction("sign") { dataBase64: String ->
      val entry = keyStore.getEntry(IDENTITY_ALIAS, null) as? KeyStore.PrivateKeyEntry
        ?: throw CodedException("ERR_NO_IDENTITY", "Identity key is absent", null)
      val signature = Signature.getInstance(SIGNATURE_ALGORITHM).apply {
        initSign(entry.privateKey)
        update(decode(dataBase64))
      }
      encode(signature.sign())
    }

    /**
     * Seals bytes under the non-exportable AES key. Used for the X25519 private
     * key and for session keys, so that reading the database off the device
     * yields ciphertext whose key cannot leave the hardware.
     *
     * The GCM nonce is generated by the platform and prefixed to the output
     * rather than chosen here: a nonce this code got wrong would be reused
     * across seals under one key, which is the failure that breaks GCM outright.
     */
    AsyncFunction("seal") { plaintextBase64: String ->
      val cipher = Cipher.getInstance("AES/GCM/NoPadding").apply {
        init(Cipher.ENCRYPT_MODE, sealingKey())
      }
      val nonce = cipher.iv
      if (nonce.size != GCM_NONCE_BYTES) {
        throw CodedException(
          "ERR_SEAL_NONCE",
          "Platform produced a ${nonce.size}-byte GCM nonce; refusing rather than guessing a layout",
          null,
        )
      }
      encode(nonce + cipher.doFinal(decode(plaintextBase64)))
    }

    AsyncFunction("unseal") { sealedBase64: String ->
      val sealed = decode(sealedBase64)
      if (sealed.size <= GCM_NONCE_BYTES) {
        throw CodedException("ERR_SEAL_FORMAT", "Sealed value is too short to contain a nonce", null)
      }
      val cipher = Cipher.getInstance("AES/GCM/NoPadding").apply {
        init(
          Cipher.DECRYPT_MODE,
          sealingKey(),
          GCMParameterSpec(GCM_TAG_BITS, sealed, 0, GCM_NONCE_BYTES),
        )
      }
      encode(cipher.doFinal(sealed, GCM_NONCE_BYTES, sealed.size - GCM_NONCE_BYTES))
    }

    /**
     * Destroys both keys. Development and factory-reset only: without the
     * sealing key every sealed row in the database becomes permanently
     * unreadable, and without the identity key the device is a stranger to its
     * own family.
     */
    AsyncFunction("destroyIdentity") {
      if (keyStore.containsAlias(IDENTITY_ALIAS)) keyStore.deleteEntry(IDENTITY_ALIAS)
      if (keyStore.containsAlias(SEAL_ALIAS)) keyStore.deleteEntry(SEAL_ALIAS)
      Unit
    }
  }

  private fun generateIdentityKey() {
    val generator = KeyPairGenerator.getInstance(KeyProperties.KEY_ALGORITHM_EC, KEYSTORE)
    val spec = KeyGenParameterSpec.Builder(IDENTITY_ALIAS, KeyProperties.PURPOSE_SIGN)
      .setAlgorithmParameterSpec(ECGenParameterSpec("secp256r1"))
      .setDigests(KeyProperties.DIGEST_SHA256)
      // Deliberately not requiring user authentication: SOS must work on a
      // locked phone, and demanding an unlock mid-emergency is a safety
      // regression (ADR 0004 §2).
      .setUserAuthenticationRequired(false)
      .build()
    generator.initialize(spec)
    generator.generateKeyPair()
  }

  private fun sealingKey(): SecretKey {
    (keyStore.getEntry(SEAL_ALIAS, null) as? KeyStore.SecretKeyEntry)?.let { return it.secretKey }

    val generator = KeyGenerator.getInstance(KeyProperties.KEY_ALGORITHM_AES, KEYSTORE)
    generator.init(
      KeyGenParameterSpec.Builder(
        SEAL_ALIAS,
        KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT,
      )
        .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
        .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
        .setKeySize(256)
        .setUserAuthenticationRequired(false)
        .build(),
    )
    return generator.generateKey()
  }

  private fun identityInfo(): Map<String, Any?> {
    val entry = keyStore.getEntry(IDENTITY_ALIAS, null) as? KeyStore.PrivateKeyEntry
      ?: throw CodedException("ERR_NO_IDENTITY", "Identity key is absent", null)
    return mapOf(
      // DER SubjectPublicKeyInfo. TypeScript derives the device id from these
      // exact bytes, so the encoding must not be reinterpreted on the way out.
      "publicKeyDer" to encode(entry.certificate.publicKey.encoded),
      "securityLevel" to securityLevel(entry.privateKey),
    )
  }

  /**
   * Reports where the key actually lives: STRONGBOX, TEE, or SOFTWARE.
   *
   * Surfaced to the user rather than assumed. A device that can only manage
   * software backing still works, but it says so — master rule 16 forbids the
   * fallback being invisible, not the fallback existing.
   */
  private fun securityLevel(privateKey: PrivateKey): String = try {
    val factory = KeyFactory.getInstance(privateKey.algorithm, KEYSTORE)
    val info = factory.getKeySpec(privateKey, KeyInfo::class.java)
    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.S) {
      when (info.securityLevel) {
        KeyProperties.SECURITY_LEVEL_STRONGBOX -> "STRONGBOX"
        KeyProperties.SECURITY_LEVEL_TRUSTED_ENVIRONMENT -> "TEE"
        KeyProperties.SECURITY_LEVEL_SOFTWARE -> "SOFTWARE"
        // The platform also reports "unknown secure". Reporting that honestly
        // beats claiming a level we did not read.
        else -> "UNKNOWN"
      }
    } else {
      @Suppress("DEPRECATION")
      if (info.isInsideSecureHardware) "TEE" else "SOFTWARE"
    }
  } catch (error: Exception) {
    // Never fail identity creation over a diagnostic. An unreadable backing
    // level is reported as unknown, not guessed at.
    "UNKNOWN"
  }

  private fun encode(bytes: ByteArray): String = Base64.encodeToString(bytes, Base64.NO_WRAP)

  private fun decode(value: String): ByteArray = try {
    Base64.decode(value, Base64.NO_WRAP)
  } catch (error: IllegalArgumentException) {
    throw CodedException("ERR_BAD_BASE64", "Value is not valid base64", error)
  }
}
